### ISSUE TITLE
PubMed article titles - trailing dot or asterisk

### ISSUE THREAD

**Issue by moqri** [SuLab/WikidataIntegrator#48] opened 2018-03-21 02:14 UTC
The trailing dots or asterisks at the end of PubMed articles need to be removed from the label and the title before being imported.

This issue also exists in Fatameh script as descibed here: 
https://www.wikidata.org/wiki/Wikidata:Requests_for_permissions/Bot/maria_research_bot

**Comment by stuppie** [comment] 2018-03-21 05:11
Duplicate of #20

**Closed by stuppie** 2018-03-21 05:11 UTC
